// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransitFeeds.Data;

#nullable disable

namespace TranstFeeds.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123151152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransitFeeds.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyLang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("agency_lang");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("agency_name");

                    b.Property<string>("AgencyPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("agency_phone");

                    b.Property<string>("AgencyTimezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("agency_timezone");

                    b.Property<string>("AgencyUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("agency_url");

                    b.Property<string>("GtfsAgencyId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gtfs_agency_id");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("TransitFeeds.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ShapeDistTraveled")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<int>("ShapeId")
                        .HasColumnType("int")
                        .HasColumnName("shape_id");

                    b.Property<decimal>("ShapePtLat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("shape_pt_lat");

                    b.Property<decimal>("ShapePtLon")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("shape_pt_lon");

                    b.Property<int>("ShapePtSequence")
                        .HasColumnType("int")
                        .HasColumnName("shape_pt_sequence");

                    b.HasKey("Id");

                    b.HasIndex("ShapeId");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("TransitFeeds.Models.ShapesMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GtfsShapeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gtfs_shape_id");

                    b.HasKey("Id");

                    b.ToTable("ShapesMaster");
                });

            modelBuilder.Entity("TransitFeeds.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GtfsStopId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gtfs_stop_id");

                    b.Property<byte?>("LocationType")
                        .HasColumnType("tinyint")
                        .HasColumnName("location_type");

                    b.Property<int?>("ParentStationId")
                        .HasColumnType("int")
                        .HasColumnName("parent_station_id");

                    b.Property<string>("StopCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stop_code");

                    b.Property<string>("StopDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stop_desc");

                    b.Property<decimal>("StopLat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("stop_lat");

                    b.Property<decimal>("StopLon")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("stop_lon");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stop_name");

                    b.Property<string>("StopTimezone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stop_timezone");

                    b.Property<string>("StopUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stop_url");

                    b.Property<byte?>("WheelchairBoarding")
                        .HasColumnType("tinyint")
                        .HasColumnName("wheelchair_boarding");

                    b.Property<string>("ZoneId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentStationId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("TransitFeeds.Models.StopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("arrival_time");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("departure_time");

                    b.Property<byte?>("DropOffType")
                        .HasColumnType("tinyint")
                        .HasColumnName("drop_off_type");

                    b.Property<byte?>("PickupType")
                        .HasColumnType("tinyint")
                        .HasColumnName("pickup_type");

                    b.Property<double?>("ShapeDistTraveled")
                        .HasColumnType("float")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<string>("StopHeadsign")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stop_headsign");

                    b.Property<int>("StopId")
                        .HasColumnType("int")
                        .HasColumnName("stop_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("int")
                        .HasColumnName("stop_sequence");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("TripId");

                    b.ToTable("StopTimes");
                });

            modelBuilder.Entity("TransitFeeds.Models.TransitCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit")
                        .HasColumnName("friday");

                    b.Property<string>("GtfsServiceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gtfs_service_id");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit")
                        .HasColumnName("monday");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit")
                        .HasColumnName("saturday");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit")
                        .HasColumnName("sunday");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit")
                        .HasColumnName("thursday");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit")
                        .HasColumnName("tuesday");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit")
                        .HasColumnName("wednesday");

                    b.HasKey("Id");

                    b.ToTable("TransitCalendar");
                });

            modelBuilder.Entity("TransitFeeds.Models.TransitRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<string>("GtfsRouteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gtfs_route_id");

                    b.Property<string>("RouteColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("route_color");

                    b.Property<string>("RouteDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("route_desc");

                    b.Property<string>("RouteLongName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("route_long_name");

                    b.Property<string>("RouteShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("route_short_name");

                    b.Property<string>("RouteTextColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("route_text_color");

                    b.Property<int?>("RouteType")
                        .HasColumnType("int")
                        .HasColumnName("route_type");

                    b.Property<string>("RouteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("route_url");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("TransitRoutes");
                });

            modelBuilder.Entity("TransitFeeds.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("block_id");

                    b.Property<byte?>("DirectionId")
                        .HasColumnType("tinyint")
                        .HasColumnName("direction_id");

                    b.Property<string>("GtfsTripId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gtfs_trip_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<int?>("ShapeId")
                        .HasColumnType("int")
                        .HasColumnName("shape_id");

                    b.Property<int>("TransitRouteId")
                        .HasColumnType("int")
                        .HasColumnName("transit_route_id");

                    b.Property<string>("TripHeadsign")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trip_headsign");

                    b.Property<string>("TripShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trip_short_name");

                    b.Property<byte?>("WheelchairAccessible")
                        .HasColumnType("tinyint")
                        .HasColumnName("wheelchair_accessible");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ShapeId");

                    b.HasIndex("TransitRouteId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TransitFeeds.Models.Shape", b =>
                {
                    b.HasOne("TransitFeeds.Models.ShapesMaster", "ShapesMaster")
                        .WithMany("Shapes")
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShapesMaster");
                });

            modelBuilder.Entity("TransitFeeds.Models.Stop", b =>
                {
                    b.HasOne("TransitFeeds.Models.Stop", "ParentStation")
                        .WithMany()
                        .HasForeignKey("ParentStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentStation");
                });

            modelBuilder.Entity("TransitFeeds.Models.StopTime", b =>
                {
                    b.HasOne("TransitFeeds.Models.Stop", "Stop")
                        .WithMany("StopTimes")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransitFeeds.Models.Trip", "Trip")
                        .WithMany("StopTimes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TransitFeeds.Models.TransitRoute", b =>
                {
                    b.HasOne("TransitFeeds.Models.Agency", "Agency")
                        .WithMany("TransitRoutes")
                        .HasForeignKey("AgencyId");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("TransitFeeds.Models.Trip", b =>
                {
                    b.HasOne("TransitFeeds.Models.TransitCalendar", "TransitCalendar")
                        .WithMany("Trips")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransitFeeds.Models.ShapesMaster", "ShapesMaster")
                        .WithMany("Trips")
                        .HasForeignKey("ShapeId");

                    b.HasOne("TransitFeeds.Models.TransitRoute", "TransitRoute")
                        .WithMany("Trips")
                        .HasForeignKey("TransitRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShapesMaster");

                    b.Navigation("TransitCalendar");

                    b.Navigation("TransitRoute");
                });

            modelBuilder.Entity("TransitFeeds.Models.Agency", b =>
                {
                    b.Navigation("TransitRoutes");
                });

            modelBuilder.Entity("TransitFeeds.Models.ShapesMaster", b =>
                {
                    b.Navigation("Shapes");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransitFeeds.Models.Stop", b =>
                {
                    b.Navigation("StopTimes");
                });

            modelBuilder.Entity("TransitFeeds.Models.TransitCalendar", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransitFeeds.Models.TransitRoute", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransitFeeds.Models.Trip", b =>
                {
                    b.Navigation("StopTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
